CREATE MEMORY TABLE SAMPLE(ID VARCHAR(16) NOT NULL PRIMARY KEY,NAME VARCHAR(50),DESCRIPTION VARCHAR(100),USE_YN CHAR(1),REG_USER VARCHAR(10))
CREATE MEMORY TABLE IDS(TABLE_NAME VARCHAR(16) NOT NULL PRIMARY KEY,NEXT_ID DECIMAL(30) NOT NULL)
CREATE MEMORY TABLE CMM_CODE(CD_TP VARCHAR(16) NOT NULL, CD VARCHAR(16) NOT NULL,CD_NAME VARCHAR(50))
SET SCHEMA PUBLIC
INSERT INTO SAMPLE VALUES('SAMPLE-00001','Runtime Environment','Foundation Layer','Y','eGov')
INSERT INTO SAMPLE VALUES('SAMPLE-00002','Runtime Environment','Persistence Layer','Y','eGov')
INSERT INTO SAMPLE VALUES('SAMPLE-00003','Runtime Environment','Presentation Layer','Y','eGov')
INSERT INTO SAMPLE VALUES('SAMPLE-00004','Runtime Environment','Business Layer','Y','eGov')
INSERT INTO SAMPLE VALUES('SAMPLE-00005','Runtime Environment','Batch Layer','Y','eGov')
INSERT INTO SAMPLE VALUES('SAMPLE-00006','Runtime Environment','Integration Layer','Y','eGov')
INSERT INTO IDS VALUES('SAMPLE',7)

INSERT INTO CMM_CODE VALUES('TP_SEX','1','남성')
INSERT INTO CMM_CODE VALUES('TP_SEX','2','여성')
INSERT INTO CMM_CODE VALUES('TP_AGE','10','10대')
INSERT INTO CMM_CODE VALUES('TP_AGE','20','20대')
INSERT INTO CMM_CODE VALUES('TP_AGE','30','30대')
INSERT INTO CMM_CODE VALUES('TP_AGE','40','40대')







